import { StyleSheet } from 'react-native'

import { authColors, authFonts, authRadii, authShadows, authSpacing } from '@/constants/tokens'

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: authColors.pageBg,
  },
  content: {
    flexGrow: 1,
    padding: authSpacing.page,
  },
  keyboardView: {
    flex: 1,
    justifyContent: 'center',
  },
  dotLayer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 28,
    inset: 0,
    opacity: 0.35,
    padding: 18,
    position: 'absolute',
  },
  dot: {
    backgroundColor: authColors.navy,
    borderRadius: 2,
    height: 3,
    width: 3,
  },
  card: {
    ...authShadows.card,
    alignSelf: 'center',
    backgroundColor: authColors.cardBg,
    borderColor: authColors.cardBorder,
    borderRadius: authRadii.card,
    borderWidth: 1,
    maxWidth: 520,
    overflow: 'hidden',
    paddingBottom: authSpacing.cardBottom,
    paddingHorizontal: authSpacing.cardX,
    paddingTop: authSpacing.cardTop,
    width: '100%',
  },
  backToSite: {
    alignSelf: 'flex-start',
    paddingBottom: 8,
  },
  backToSiteText: {
    color: authColors.softMutedBlue,
    fontFamily: authFonts.body,
    fontSize: 13,
    fontWeight: '600',
  },
  header: {
    paddingBottom: 16,
  },
  logo: {
    height: 52,
    width: 156,
  },
  progressRow: {
    paddingBottom: 16,
    paddingTop: 10,
  },
  progressDot: {
    backgroundColor: authColors.slateLight,
    borderRadius: 99,
    height: 7,
  },
  progressDotActive: {
    backgroundColor: authColors.skyBlue,
  },
  progressDotDone: {
    backgroundColor: authColors.success,
  },
  heading: {
    color: authColors.navy,
    fontFamily: authFonts.heading,
    fontSize: 22,
    fontWeight: '800',
    lineHeight: 27,
    textAlign: 'center',
  },
  subtitle: {
    color: authColors.mutedBlue,
    fontFamily: authFonts.body,
    fontSize: 13,
    fontWeight: '400',
    lineHeight: 20,
    paddingTop: 8,
    textAlign: 'center',
  },
  infoBanner: {
    alignItems: 'center',
    backgroundColor: authColors.successBg,
    borderColor: authColors.successBorder,
    borderRadius: authRadii.error,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  infoText: {
    color: authColors.successDark,
    flex: 1,
    fontFamily: authFonts.body,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  subheading: {
    color: authColors.navy,
    fontFamily: authFonts.heading,
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  form: {
    width: '100%',
  },
  label: {
    color: authColors.cerulean,
    fontFamily: authFonts.body,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.7,
  },
  caption: {
    color: authColors.softMutedBlue,
    fontFamily: authFonts.body,
    fontSize: 12,
  },
  input: {
    backgroundColor: authColors.inputBg,
    borderColor: authColors.borderBlue,
    borderRadius: authRadii.input,
    borderWidth: 1.5,
    color: authColors.navy,
    fontFamily: authFonts.body,
    fontSize: 14,
    fontWeight: '500',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  passwordRow: {
    alignItems: 'center',
    backgroundColor: authColors.inputBg,
    borderColor: authColors.borderBlue,
    borderRadius: authRadii.input,
    borderWidth: 1.5,
    flexDirection: 'row',
  },
  passwordInput: {
    color: authColors.navy,
    flex: 1,
    fontFamily: authFonts.body,
    fontSize: 14,
    fontWeight: '500',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  eyeButton: {
    padding: 12,
  },
  strengthRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 3,
    marginTop: 6,
  },
  strengthBar: {
    backgroundColor: authColors.strengthTrack,
    borderRadius: 99,
    flex: 1,
    height: 3,
  },
  strengthBarWeak: {
    backgroundColor: authColors.weak,
  },
  strengthBarFair: {
    backgroundColor: authColors.warning,
  },
  strengthBarGood: {
    backgroundColor: authColors.success,
  },
  strengthLabel: {
    fontFamily: authFonts.body,
    fontSize: 11,
    fontWeight: '700',
    minWidth: 40,
    textAlign: 'right',
  },
  strengthLabelWeak: {
    color: authColors.weak,
  },
  strengthLabelFair: {
    color: authColors.warning,
  },
  strengthLabelGood: {
    color: authColors.success,
  },
  programGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  programButton: {
    backgroundColor: authColors.inputBg,
    borderColor: authColors.borderBlue,
    borderRadius: 9,
    borderWidth: 1.5,
    minHeight: 82,
    paddingHorizontal: 10,
    paddingVertical: 10,
    width: '31%',
  },
  programButtonSelected: {
    backgroundColor: authColors.studentSoft,
    borderColor: authColors.skyBlue,
  },
  programCode: {
    color: authColors.cerulean,
    fontFamily: authFonts.body,
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
  },
  programName: {
    color: authColors.mutedBlue,
    fontFamily: authFonts.body,
    fontSize: 11,
    lineHeight: 15,
    paddingTop: 6,
    textAlign: 'center',
  },
  programTextSelected: {
    color: authColors.cerulean,
  },
  yearButton: {
    alignItems: 'center',
    backgroundColor: authColors.inputBg,
    borderColor: authColors.borderBlue,
    borderRadius: authRadii.input,
    borderWidth: 1.5,
    padding: 14,
  },
  yearButtonSelected: {
    backgroundColor: authColors.studentSoft,
    borderColor: authColors.skyBlue,
  },
  yearText: {
    color: authColors.navy,
    fontFamily: authFonts.heading,
    fontSize: 18,
    fontWeight: '800',
  },
  errorText: {
    backgroundColor: authColors.dangerBg,
    borderColor: authColors.dangerBorder,
    borderRadius: authRadii.error,
    borderWidth: 1,
    color: authColors.danger,
    fontFamily: authFonts.body,
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 19,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  successText: {
    color: authColors.success,
    fontFamily: authFonts.body,
    fontSize: 14,
    fontWeight: '700',
  },
  actionRow: {
    width: '100%',
  },
  primaryButton: {
    ...authShadows.button,
    alignItems: 'center',
    backgroundColor: authColors.cerulean,
    borderRadius: authRadii.input,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  primaryButtonText: {
    color: authColors.white,
    fontFamily: authFonts.body,
    fontSize: 14,
    fontWeight: '700',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: authColors.cardBg,
    borderColor: authColors.borderBlue,
    borderRadius: authRadii.input,
    borderWidth: 1.5,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  secondaryButtonText: {
    color: authColors.navy,
    fontFamily: authFonts.body,
    fontSize: 14,
    fontWeight: '700',
  },
  linkButton: {
    alignItems: 'center',
    padding: 8,
  },
  linkText: {
    color: authColors.mutedBlue,
    fontFamily: authFonts.body,
    fontSize: 14,
  },
  linkTextStrong: {
    color: authColors.skyBlue,
    fontWeight: '700',
  },
})
