import { StyleSheet } from 'react-native'

import { authColors, authFonts, authRadii, authShadows, authSpacing } from '@/constants/tokens'

export default StyleSheet.create({
  gradient: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    backgroundColor: authColors.pageBg,
  },
  content: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: authSpacing.page,
  },
  keyboardView: {
    flex: 1,
    justifyContent: 'center',
  },
  card: {
    ...authShadows.card,
    alignSelf: 'center',
    backgroundColor: authColors.cardBg,
    borderColor: authColors.cardBorder,
    borderRadius: authRadii.card,
    borderWidth: 1,
    maxWidth: 440,
    overflow: 'hidden',
    paddingBottom: authSpacing.cardBottom,
    paddingHorizontal: authSpacing.cardX,
    paddingTop: authSpacing.cardTop,
    width: '100%',
  },
  backLink: {
    alignSelf: 'flex-start',
    paddingBottom: 4,
  },
  backLinkText: {
    color: authColors.softMutedBlue,
    fontFamily: authFonts.body,
    fontSize: 13,
    fontWeight: '600',
  },
  header: {
    paddingBottom: 14,
  },
  logo: {
    height: 52,
    width: 156,
  },
  brandText: {
    color: authColors.navy,
    fontFamily: authFonts.heading,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 1,
  },
  roleHintRow: {
    alignItems: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    paddingBottom: 18,
  },
  roleHintText: {
    color: authColors.softMutedBlue,
    fontFamily: authFonts.body,
    fontSize: 12,
    fontWeight: '500',
  },
  rolePill: {
    backgroundColor: authColors.inputBgStrong,
    borderColor: authColors.borderBlue,
    borderRadius: authRadii.badge,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  rolePillText: {
    color: authColors.cerulean,
    fontFamily: authFonts.body,
    fontSize: 12,
    fontWeight: '700',
  },
  changeText: {
    color: authColors.skyBlue,
    fontFamily: authFonts.body,
    fontSize: 12,
    fontWeight: '700',
  },
  heading: {
    color: authColors.navy,
    fontFamily: authFonts.heading,
    fontSize: 22,
    fontWeight: '800',
    lineHeight: 27,
    textAlign: 'center',
  },
  subtitle: {
    color: authColors.mutedBlue,
    fontFamily: authFonts.body,
    fontSize: 13,
    fontWeight: '400',
    lineHeight: 20,
    paddingBottom: 22,
    paddingTop: 8,
    textAlign: 'center',
  },
  form: {
    width: '100%',
  },
  labelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  label: {
    color: authColors.cerulean,
    fontFamily: authFonts.body,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.7,
  },
  input: {
    backgroundColor: authColors.inputBg,
    borderColor: authColors.borderBlue,
    borderRadius: authRadii.input,
    borderWidth: 1.5,
    color: authColors.navy,
    fontFamily: authFonts.body,
    fontSize: 14,
    fontWeight: '500',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  badge: {
    backgroundColor: authColors.successBg,
    borderColor: authColors.successBorder,
    borderRadius: authRadii.badge,
    borderWidth: 1,
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  badgeText: {
    color: authColors.successDark,
    fontFamily: authFonts.body,
    fontSize: 11,
    fontWeight: '700',
  },
  forgotText: {
    color: authColors.skyBlue,
    fontFamily: authFonts.body,
    fontSize: 12,
    fontWeight: '600',
  },
  passwordRow: {
    alignItems: 'center',
    backgroundColor: authColors.inputBg,
    borderColor: authColors.borderBlue,
    borderRadius: authRadii.input,
    borderWidth: 1.5,
    flexDirection: 'row',
  },
  passwordInput: {
    color: authColors.navy,
    flex: 1,
    fontFamily: authFonts.body,
    fontSize: 14,
    fontWeight: '500',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  eyeButton: {
    padding: 12,
  },
  errorText: {
    backgroundColor: authColors.dangerBg,
    borderColor: authColors.dangerBorder,
    borderRadius: authRadii.error,
    borderWidth: 1,
    color: authColors.danger,
    fontFamily: authFonts.body,
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 19,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  primaryButton: {
    ...authShadows.button,
    alignItems: 'center',
    backgroundColor: authColors.cerulean,
    borderRadius: authRadii.input,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  primaryButtonText: {
    color: authColors.white,
    fontFamily: authFonts.body,
    fontSize: 14,
    fontWeight: '700',
  },
  divider: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    paddingVertical: 4,
  },
  dividerLine: {
    backgroundColor: authColors.dividerBlue,
    flex: 1,
    height: 1,
  },
  dividerText: {
    color: authColors.softMutedBlue,
    fontFamily: authFonts.body,
    fontSize: 12,
    fontWeight: '600',
  },
  socialButton: {
    ...authShadows.social,
    alignItems: 'center',
    backgroundColor: authColors.cardBg,
    borderColor: authColors.borderBlue,
    borderRadius: authRadii.input,
    borderWidth: 1.5,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    minHeight: 46,
  },
  googleMark: {
    color: authColors.google,
    fontFamily: authFonts.body,
    fontSize: 18,
    fontWeight: '800',
  },
  facebookMark: {
    color: authColors.facebook,
    fontFamily: authFonts.body,
    fontSize: 20,
    fontWeight: '900',
  },
  socialText: {
    color: authColors.navy,
    fontFamily: authFonts.body,
    fontSize: 14,
    fontWeight: '600',
  },
  linkButton: {
    alignItems: 'center',
    padding: 8,
  },
  linkText: {
    color: authColors.mutedBlue,
    fontFamily: authFonts.body,
    fontSize: 14,
  },
  linkTextStrong: {
    color: authColors.skyBlue,
    fontWeight: '700',
  },
})
